language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
    - sudo apt-get install parallel
    - composer install --prefer-source
    - bin/composer install --prefer-source
    - git config --global user.name travis-ci
    - git config --global user.email travis@example.com
    - wget https://phar.phpunit.de/phpcov.phar
    - mkdir -p /tmp/coverage/tests/Composer/Test/
script:
    - ls -d tests/Composer/Test/* | grep -Ev "(Fixtures|Mock)" | parallel --gnu --keep-order 'echo "Running {} tests"; ./vendor/bin/phpunit -c tests/complete.phpunit.xml {};' || exit 1
    - php phpcov.phar merge --clover coverage.clover /tmp/coverage/tests/Composer/Test

after-script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

git:
  depth: 5
