name: "Autoloader"

on:
  push:
    paths-ignore:
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'doc/**'

permissions:
  contents: read

jobs:
  tests:
    name: "Autoloader"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Install Composer dependencies"
        run: "composer config platform --unset && composer install"

      - name: "Dump autoloader in the test directory using latest Composer"
        run: "./bin/composer install -d tests/Composer/Test/Autoload/MinimumVersionSupport"

      - name: "Install oldest supported PHP version for autoloader"
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0
        with:
          coverage: "none"
          extensions: "intl, zip"
          ini-values: "memory_limit=-1"
          php-version: "5.6"

      - name: "Check the autoloader can be executed"
        run: "php main.php"
        working-directory: tests/Composer/Test/Autoload/MinimumVersionSupport
